---
archetypeDir:               "themes/ddeus_v1/archetypes"
# hostname (and path) to the root, e.g. http://spf13.com/
baseURL:                    "/"
# include content marked as draft
buildDrafts:                false
# include content with publishdate in the future
buildFuture:                false
# include content already expired
buildExpired:               false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs:               false
canonifyURLs:               false
# config file (default is path/config.yaml|json|toml)
config:                     "config.yaml"
contentDir:                 "content"
dataDir:                    "themes/ddeus_v1/data"
defaultExtension:           "html"
defaultLayout:              "post"
# Missing translations will default to this content language
defaultContentLanguage:     "en"
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir: false
disableLiveReload:          false
# Do not build RSS files
disableRSS:                 true
# Do not build Sitemap file
disableSitemap:             false
# Build robots.txt file
enableRobotsTXT:            true
# Do not render 404 page
disable404:                 false
# Do not inject generator meta tag on homepage
disableHugoGeneratorInject: true
# edit new content with this editor, if provided
editor:                     "atom"
# Enable Emoji emoticons support for page content.
# See www.emoji-cheat-sheet.com
enableEmoji:                true
# google analytics tracking id
googleAnalytics:            "UA-22618780-6"
languageCode:               ""
layoutDir:                  "themes/ddeus_v1/layouts"
# "yaml", "toml", "json"
metaDataFormat:             "yaml"
newContentEditor:           ""
# Don't sync permission mode of files
noChmod:                    false
# Don't sync modification time of files
noTimes:                    false
paginate:                   10
paginatePath:               "page"
permalinks:
# Pluralize titles in lists using inflect
pluralizeListTitles:        true
# Preserve special characters in taxonomy names ("Gérard Depardieu" vs "Gerard Depardieu")
preserveTaxonomyNames:      false
# filesystem path to write files to
publishDir:                 "public"
# default sitemap configuration map
sitemap:
staticDir:                  "themes/ddeus_v1/static"
# display memory and timing of different steps of the program
stepAnalysis:               true
# theme to use (located by default in /themes/THEMENAME/)
themesDir:                  "themes"
theme:                      "ddeus_v1"
title:                      "ddeus"
# if true, use /filename.html instead of /filename/
uglyURLs:                   false
watch:                      true

taxonomies:
  tag: "tags"

params:
  Author: Matthias Jordan
  Description: A Hugo / flexboxgrid ddeus_v1plate
  Attribution: Made with ♡ in Santa Monica, California, USA
---
